language: node_js

node_js:
    - 'node'

# TODO: could cache docker layers for a faster build, tho prolly unnecessary for now.

install:
    - yarn --cwd ./web
    - yarn --cwd ./server

before_script:
    - yarn --cwd ./web lint || yarn --cwd ./server lint

script:
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml build

cache:
    yarn: true
    directories:
        - node_modules

sudo: true

services:
    - docker
