language: node_js

node_js:
    - 'node'

install:
    - yarn --cwd ./web install
    - yarn --cwd ./server install

script:
    - yarn --cwd ./web lint
    - yarn --cwd ./server lint

cache:
    yarn: true
    directories:
        - node_modules

sudo: false
