version: '3.4'
services:
    test:
        image: node:10.10.0
        working_dir: /usr/src/app/server
        depends_on:
            - postgres
        volumes:
            - .:/usr/src/app # mounting whole dir so jest can look at .git
            - node_modules:/usr/src/app/server/node_modules
        environment:
            DB_HOST: postgres:5432
        env_file: .env
    test-ci:
        image: node:10.10.0
        depends_on:
            - postgres
        volumes:
            - ./server:/usr/src/app
            - node_modules:/usr/src/app/node_modules
        environment:
            DB_HOST: postgres:5432
            ? FILMKEY
            ? GAMEKEY
    postgres:
        image: cs4920-postgres:prod
        build:
            target: prod
    server: # should not be used, only here to make the definition valid
        image: node:10.10.0-alpine
