version: '3.4'
services:
    server:
        image: node:10.10.0-alpine
        # runs yarn at runtime so mounts are active
        command: sh -c "yarn --no-progress && yarn test" # TODO: forward arguments into this
        volumes:
            - ./server:/usr/src/app
    postgres:
        image: cs4920-postgres:prod
        build:
            target: prod
