version: '3'
services:
    server:
        image: node:10.10.0-alpine
        working_dir: /usr/src/app/server
        command: sh -c "yarn --no-progress && yarn start"
        volumes:
            - ./web:/usr/src/app/web
            - ./server:/usr/src/app/server
            - node_modules:/usr/src/app/server/node_modules # use a volume for node_modules specific to the container
        depends_on:
            - postgres
        ports:
            - '8080:8080'
    postgres:
        build:
            context: ./database
            dockerfile: Dockerfile
        environment:
            POSTGRES_DB: appdb
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - '5433:5432'
volumes:
    ? db-data
    ? node_modules
