# this config does not work by itself, is extended by
# `docker-compose.override.yml` for dev and
# `docker-compose.prod.yml` for prod
version: '3.4'
services:
    server:
        working_dir: /usr/src/app
        volumes:
            - node_modules:/usr/src/app/node_modules # use a volume for node_modules specific to the container
        depends_on:
            - postgres
        ports:
            - '8080:8080'
        environment:
            DB_HOST: postgres:5432
    postgres:
        build:
            context: ./database
        environment:
            POSTGRES_DB: appdb
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
volumes:
    ? db-data
    ? node_modules
