version: '3'
services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    depends_on:
      - postgres
    ports:
     - "3000:3000"
  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
