# dev config - automatically used for `docker-compose up`
version: '3'
services:
    server:
        image: node:10.10.0-alpine
        # runs yarn at runtime so mounts are active
        command: sh -c "yarn --no-progress && yarn start"
        volumes:
            - ./server:/usr/src/app
